database: 
  pv:
    storage: 1Gi
    path: /data/db
  image: mongo:4.4.6
  replicas: 1

backend:
  replicas: 3
  image: backend:latest
  imagePullPolicy: IfNotPresent

frontend:
  replicas: 3
  image: frontend4:latest
  imagePullPolicy: IfNotPresent
  
