apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}-apipod
  labels: 
    role: api
    env: demo
spec: 
  replicas: {{ .Values.backend.replicas }}
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector: 
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
      - name: api
        image: {{ .Values.backend.image }}
        imagePullPolicy: {{ .Values.backend.imagePullPolicy }}
        env:
          - name: MONGO_CONN_STR
            value: mongodb://{{ .Release.Name }}-mongodbsvc:27017/todo?directConnection=true
          - name: MONGO_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mongodbsecret
                key: username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-mongodbsecret
                key: password
        ports:
        - containerPort: 3500
        livenessProbe: 
          httpGet:
            path: /ok
            port: 3500
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ok
            port: 3500
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
