apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    role: frontend
    env: demo
spec: 
  replicas: {{ .Values.frontend.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}
        env:
          - name: REACT_APP_BACKEND_URL
            value: http://172.18.0.2:30050/api/tasks # If SSL is configured keep https other http is fine
        ports:
        - containerPort: 3000
