apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-frontendsvc

spec:
  type: NodePort

  selector:
    role: frontend

  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 30080
